name: Lint Success on PR

on:
  pull_request:
    branches:
      - '**'

jobs:
  linting-job:
    name: Perform linting on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run linting check
        run: npm run lint

      - name: Run formatter
        run: npm run format
